stages:
  - build
  - deploy

build:
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run build
  cache:
    untracked: true
    paths:
    - node_modules/
  only:
    - master
  stage: build
  tags: 
    - demo

deploy:
  script:
    - mkdir -p /data/yjb/frontend/
    - rm -rf  /data/yjb/frontend/*
    - cp -r dist/* /data/yjb/frontend/
  only:
    - master
  stage: deploy
  tags: 
    - demo
  variables:
    GIT_STRATEGY: none


nginx:
  script:
    - cp ci/conf/demo.nginx.conf /etc/nginx/sites-enabled/yjb-frontend.conf
    - service nginx restart
  only:
    - master
  stage: deploy
  tags: 
    - demo